#pragma once

#include <sdkddkver.h>
#include "SList.h"
#include "Vector.h"
#include "HashMap.h"
#include "Datum.h"
#include "Scope.h"
#include "Attributed.h"
#include "XMLParseMaster.h"
#include "XMLParseHelperTable.h"
#include "XMLParseHelperWorld.h"
#include "XMLParseHelperSector.h"
#include "XMLParseHelperEntity.h"
#include "World.h"
#include "Sector.h"
#include "Entity.h"
#include "Factory.h"
#include "WorldState.h"
#include "GameClock.h"
#include "GameTime.h"
#include "DummyStruct.h"
#include <stdexcept>